{% set version = "0.7.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-snowballc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SnowballC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SnowballC/SnowballC_{{ version }}.tar.gz
  sha256: 753cf13f3206751662c03b1cf39bce9e680024f6d9f8503b836a83797181c034

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('SnowballC')"           # [not win]
    - "\"%R%\" -e \"library('SnowballC')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/r-temis/
  license: BSD-3-Clause
  summary: An R interface to the C libstemmer library that implements Porter's word stemming algorithm for collapsing words to a common root to aid comparison of vocabulary. Currently supported languages are Danish, Dutch, English, Finnish, French, German, Hungarian, Italian, Norwegian, Portuguese, Romanian, Russian, Spanish,
    Swedish and Turkish.
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - croth1

# Package: SnowballC
# Type: Package
# Version: 0.6.0
# Date: 2019-01-07
# Title: Snowball Stemmers Based on the C 'libstemmer' UTF-8 Library
# Authors@R: person("Milan", "Bouchet-Valat", email="nalimilan@club.fr", role=c("aut", "cre"))
# Description: An R interface to the C 'libstemmer' library that implements Porter's word stemming algorithm for collapsing words to a common root to aid comparison of vocabulary. Currently supported languages are Danish, Dutch, English, Finnish, French, German, Hungarian, Italian, Norwegian, Portuguese, Romanian, Russian, Spanish, Swedish and Turkish.
# License: BSD_3_clause + file LICENSE
# Copyright: Dr Martin Porter (2001) and Richard Boulton (2004, 2005) for the 'libstemmer' C library, and Milan Bouchet-Valat (2013) for the R package contents.
# URL: https://r-forge.r-project.org/projects/r-temis/
# BugReports: https://r-forge.r-project.org/tracker/?group_id=1437
# NeedsCompilation: yes
# Packaged: 2019-01-08 13:36:02 UTC; milan
# Author: Milan Bouchet-Valat [aut, cre]
# Maintainer: Milan Bouchet-Valat <nalimilan@club.fr>
# Repository: CRAN
# Date/Publication: 2019-01-15 16:10:03 UTC
