travis:
  secure:
    BINSTAR_TOKEN: k+iKTY/OW8m9C50GzHX1BNdX11/7quJTCCn8gklaXehBDfqzNVN6GYoMh+PrvQR9LfuKcsL4jXyj2GvW6hy6rB8KtCrNC80xDmqyY7AHf55WfPTzhKXI4FT3YFZNyJwvF505NkcoWe5yZN5dBY5h83kVkWAGH4lDkG/3hCpxPuAvbtWaQaA2tfQMeW/D4xZ7Q0yKb7TCz/R6wi82Jgmk3bmo7ekratj/+Ez8Xkjy4d+m0w1UZHsN5Xz6sPxzuFXULjQtiVxv8aFdDC9If69ZcsRrXCzlJ1Sk4XU+xLTTAWe1rQ0U6e6LIRD+HMpuaFw0xHwhg9VTFY20faZGfjBr5ozVVO2BdJ5CFTAys0dxcMAPgcGUTR4UqzTWOf47u9H+cCpGAgZd3OI3kSCNRRzRjhu9ITdYk3WlE+CMwbJF6NcLDfIkOOL7cKW4HsFazII6FhTEqIk/jEQlhb8bf96YQjn5+nLO/lZ7x4+LpH6DqmxA2DLsVP0LIg3YFGNqyFfOrAgGyFgZBjn3djl4+ewUU9es2yXeH1PwN24DjmmmnDBg8ZkV28+Secw9g3Mx5AaS5oFgOKqBX5jzOo5TFkeUf5SMgwNhAoVC3tT8zbzZ0axCTjik8+1dfVwYnmXvU5rX+vhI3WpoeRTqVZWJY0wNqG/NfpPbZP5c/XSbE75NvZA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
